name: Build Docker Image for Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  NODE_VERSION: 20


jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repositorycontainer registry push test
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          check-latest: true
          cache: npm

      - name: Install dependencies
        run: |
          npm ci

      - name: Build project
        run: npm run build

      - name: Cache setup
        uses: actions/cache@v4
        with:
          path: ./*
          key: ${{ github.ref }}-${{ github.sha }}-setup


      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Extract PR ID and generate tags
        id: meta
        run: |
          LOWERCASE_IMAGE_NAME=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
          echo "PR_ID=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "IMAGE_NAME=${LOWERCASE_IMAGE_NAME}" >> $GITHUB_ENV
          echo "TAG=test-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "Generated tag: test-${{ github.event.pull_request.number }} for $LOWERCASE_IMAGE_NAME"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test-${{ github.event.pull_request.number }}
